import type { Prisma } from "@prisma/client";
import type { LedgerEntry } from "@/modules/ledger/entities/ledger-entry.entity";

export interface CreateLedgerEntryInput {
  /** Pre-generated by the caller (WalletService) — see schema.prisma's LedgerEntry doc comment for why. */
  id: string;
  /** Pre-generated WalletTransaction id this entry belongs to (or, for transfer(), the shared entry for both sides' rows). */
  transactionId: string;
  debitAccount: string;
  creditAccount: string;
  amount: number;
  currency?: string;
  reference?: string | null;
  referenceType?: string | null;
  description?: string | null;
}

export interface LedgerListFilter {
  debitAccount?: string;
  creditAccount?: string;
  reference?: string;
  referenceType?: string;
  from?: Date;
  to?: Date;
  page: number;
  pageSize: number;
}

/**
 * The service layer depends on THIS interface, never on `@/lib/prisma`
 * directly — see repositories/ledger.prisma-repository.ts for the real
 * implementation and .in-memory-repository.ts for the one tests inject.
 *
 * `createEntry` accepts an optional Prisma transaction client so
 * WalletService can call it from inside its own locked `$transaction` —
 * the balance change and the ledger entry must commit or roll back
 * together, never as two independent writes.
 */
export interface ILedgerRepository {
  createEntry(input: CreateLedgerEntryInput, tx?: Prisma.TransactionClient): Promise<LedgerEntry>;
  findById(id: string): Promise<LedgerEntry | null>;
  listForTransaction(transactionId: string): Promise<LedgerEntry[]>;
  list(filter: LedgerListFilter): Promise<{ items: LedgerEntry[]; total: number }>;
}
