import type { GameMode, MatchStatus } from "@prisma/client";
import type { Match, MatchSummary } from "@/modules/match-engine/entities/match.entity";

export interface CreateMatchInput {
  /** Pre-generated by the caller (see MatchEngineService.create) — the bet debit needs a real matchId for its idempotency key before this row exists. Falls back to the DB default if omitted. */
  id?: string;
  matchNumber: string;
  userId: string;
  betAmount: number;
  goalAmount: number;
  balanceBefore: number;
  seed: string;
  tokenHash: string;
  targetMultiplier: number;
  mode: GameMode;
  configVersion: number | null;
  presetKey: string | null;
  engineParams: Record<string, number | boolean>;
  goalSnapshot: Record<string, unknown>;
  antiCheatSnapshot: Record<string, number>;
  engineVersion: string | null;
  ip: string | null;
  userAgent: string | null;
  device: string | null;
  os: string | null;
}

export type UpdateMatchInput = Partial<
  Pick<
    Match,
    | "status"
    | "platformsPassed"
    | "multiplier"
    | "potentialPayout"
    | "payout"
    | "balanceAfter"
    | "startedAt"
    | "resolvedAt"
    | "durationSeconds"
    | "longestStreak"
    | "collisionCount"
    | "avgSpeed"
    | "riskScore"
    | "invalidationReason"
  >
>;

export interface AdminMatchListFilter {
  status?: MatchStatus;
  mode?: GameMode;
  userId?: string;
  from?: Date;
  to?: Date;
  page: number;
  pageSize: number;
}

/**
 * The service layer depends on THIS interface, never on `@/lib/prisma`
 * directly — see repositories/match.prisma-repository.ts for the real
 * implementation and .in-memory-repository.ts for the one tests inject.
 */
export interface IMatchRepository {
  findById(id: string): Promise<Match | null>;
  create(input: CreateMatchInput): Promise<Match>;
  update(id: string, patch: UpdateMatchInput): Promise<Match>;
  /** Player-facing history — resolved matches only, most recent first. */
  listForUser(userId: string, limit: number): Promise<MatchSummary[]>;
  listAdmin(filter: AdminMatchListFilter): Promise<{ items: MatchSummary[]; total: number }>;
}
