const LOGIN_CHARS = "abcdefghjkmnpqrstuvwxyz23456789"; // no o/0/i/1 — avoids visual ambiguity if ever surfaced (e.g. admin search)

function randomChar(charset: string): string {
  return charset[Math.floor(Math.random() * charset.length)];
}

/**
 * Player signup no longer collects username/email (phone + password is the
 * login identifier — see AuthService.login()) but `User.username`/`.email`
 * are still required+unique columns, so both are auto-generated and never
 * shown to the player. Uniqueness is the CALLER's responsibility, same
 * retry-on-collision pattern as generateReferralCode/generateDemoLogin.
 */
export function generateAutoUsername(): string {
  const suffix = Array.from({ length: 10 }, () => randomChar(LOGIN_CHARS)).join("");
  return `player_${suffix}`;
}

/** No dedicated inbox exists for phone-only signups — a synthetic address just satisfies User.email's unique/NOT NULL constraint, same convention as demo-accounts' demoEmailFor(). */
export function autoEmailFor(username: string): string {
  return `${username}@player.helixcoin.internal`;
}

/**
 * True for both this module's synthetic addresses and demo-accounts'
 * (`@demo.helixcoin.internal`, see demo-accounts/utils/credentials.util.ts's
 * demoEmailFor()) — undeliverable, unresolvable domains that exist only to
 * satisfy User.email's unique/NOT NULL constraint. Callers that hand a
 * user's email to something outside our system (e.g. a payment gateway's
 * `client.email`) must check this first: gateways can silently reject a
 * request whose email domain has no MX record / isn't a real mailbox,
 * exactly the kind of failure that shows up as an opaque non-OK status with
 * no error message.
 */
export function isAutoGeneratedEmail(email: string): boolean {
  return email.endsWith("@player.helixcoin.internal") || email.endsWith("@demo.helixcoin.internal");
}

/**
 * Frees up User.email/username's unique constraints on soft-delete (see
 * UserManagementService.softDelete's doc comment) — keyed off the row's own
 * `id`, which is already globally unique, so unlike generateAutoUsername()
 * above this never needs a collision-retry loop. Kept within usernameSchema's
 * 24-char/`[a-z0-9_]+` limits (auth.validator.ts) even though tombstone
 * writes bypass that schema, so the value stays well-formed if anything ever
 * re-validates it (e.g. an admin edit form).
 */
export function tombstoneUsernameFor(id: string): string {
  return `del_${id.replace(/-/g, "").slice(-16)}`;
}

/** Mirrors autoEmailFor()'s convention — a distinct domain (`@deleted.` vs `@player.`) so a deleted account's tombstone email is visually obvious if it ever surfaces (e.g. admin search, audit log). */
export function tombstoneEmailFor(id: string): string {
  return `${tombstoneUsernameFor(id)}@deleted.helixcoin.internal`;
}
