import { describe, expect, it } from "vitest";
import { generateAutoUsername, autoEmailFor, isAutoGeneratedEmail } from "@/modules/identity/utils/auto-identity.util";

describe("isAutoGeneratedEmail", () => {
  it("flags a phone-signup player's synthetic address", () => {
    const username = generateAutoUsername();
    expect(isAutoGeneratedEmail(autoEmailFor(username))).toBe(true);
  });

  it("flags a Conta Demo synthetic address", () => {
    expect(isAutoGeneratedEmail("demo47291@demo.helixcoin.internal")).toBe(true);
  });

  it("does not flag a real email", () => {
    expect(isAutoGeneratedEmail("joao@gmail.com")).toBe(false);
  });

  it("only matches the synthetic domain at the end of the address, not merely as a substring", () => {
    expect(isAutoGeneratedEmail("real@player.helixcoin.internal.example.com")).toBe(false);
  });
});
