import type {
  WalletBalances,
  WalletTransaction,
  WalletAdminSummary,
  TransactionType,
  TransactionStatus,
  WalletAccount,
} from "@/modules/wallet/entities/wallet.entity";
import type { LedgerEntry } from "@/modules/ledger/entities/ledger-entry.entity";

export interface CreateWalletTransactionInput {
  /** Pre-generated by the caller (WalletService) — see LedgerEntry's schema doc comment for the creation-order rationale. */
  id: string;
  walletId: string;
  userId: string;
  ledgerId: string | null;
  type: TransactionType;
  account: WalletAccount;
  amount: number;
  balanceBefore: number | null;
  balanceAfter: number | null;
  origin: string;
  originId?: string | null;
  description?: string | null;
  status?: TransactionStatus;
  idempotencyKey?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface CreateLedgerEntryInput {
  id: string;
  transactionId: string;
  debitAccount: string;
  creditAccount: string;
  amount: number;
  currency?: string;
  reference?: string | null;
  referenceType?: string | null;
  description?: string | null;
}

export interface WalletBalanceDelta {
  main?: number;
  locked?: number;
  bonus?: number;
}

/** Bound to one locked wallet + one open DB transaction — every method here commits or rolls back together. */
export interface LockedWalletCtx {
  balances: WalletBalances;
  applyDelta(delta: WalletBalanceDelta): Promise<WalletBalances>;
  createWalletTransaction(input: CreateWalletTransactionInput): Promise<WalletTransaction>;
  createLedgerEntry(input: CreateLedgerEntryInput): Promise<LedgerEntry>;
}

export interface TransactionListFilter {
  userId?: string;
  type?: TransactionType;
  status?: TransactionStatus;
  origin?: string;
  from?: Date;
  to?: Date;
  minAmount?: number;
  maxAmount?: number;
  page: number;
  pageSize: number;
}

export interface WalletListFilter {
  search?: string;
  page: number;
  pageSize: number;
}

/**
 * The service layer depends on THIS interface, never on `@/lib/prisma`
 * directly — see repositories/wallet.prisma-repository.ts for the real
 * implementation (Postgres `SELECT ... FOR UPDATE` row locking) and
 * .in-memory-repository.ts for the one tests inject (per-userId async
 * mutex — proves serialization logic, not the real DB lock, see this
 * module's README).
 */
export interface IWalletRepository {
  /** Read-only upsert — creates a zero-balance wallet if the user has none yet. No lock taken. */
  getOrCreateWallet(userId: string): Promise<WalletBalances>;
  /** Opens one DB transaction, locks the wallet row, and runs `fn` — every mutating WalletService method goes through this. */
  withLockedWallet<T>(userId: string, fn: (ctx: LockedWalletCtx) => Promise<T>): Promise<T>;
  /** Used only by transfer() — locks BOTH wallets in a fixed order (never call-argument order) inside one transaction, to avoid cross-transfer deadlocks. */
  withLockedWalletPair<T>(
    userIdA: string,
    userIdB: string,
    fn: (ctxA: LockedWalletCtx, ctxB: LockedWalletCtx) => Promise<T>
  ): Promise<T>;
  findTransactionByIdempotencyKey(key: string): Promise<WalletTransaction | null>;
  getTransactionById(id: string): Promise<WalletTransaction | null>;
  listTransactions(filter: TransactionListFilter): Promise<{ items: WalletTransaction[]; total: number }>;
  listWalletsAdmin(filter: WalletListFilter): Promise<{ items: WalletAdminSummary[]; total: number }>;
}
