import { BusinessRuleError, ExternalServiceError, ForbiddenError, NotFoundError } from "@/server/errors";
import { eventBus } from "@/server/events";
import { encrypt, decrypt } from "@/server/security/crypto-utils";
import { GatewayTimeoutError } from "@/modules/payments/errors";
import { WalletService } from "@/modules/wallet/services/wallet.service";
import type { WalletActor } from "@/modules/wallet/entities/wallet.entity";
import type { IUserRepository } from "@/modules/identity/interfaces/user-repository.interface";
import { isAutoGeneratedEmail } from "@/modules/identity/utils/auto-identity.util";
import { MockProvider } from "@/modules/payments/providers/mock/mock.provider";
import { ProviderFactory } from "@/modules/payments/factories/provider.factory";
import { GatewayRouterService } from "@/modules/payments/services/gateway-router.service";
import { WebhookDispatcherService } from "@/modules/payments/services/webhook-dispatcher.service";
import { PAYMENT_EVENTS } from "@/modules/payments/events/payments.events";
import { PAYMENT_IDEMPOTENCY_KEYS, maskPixKey } from "@/modules/payments/constants/payments.constants";
import type { IDepositRepository } from "@/modules/payments/interfaces/deposit-repository.interface";
import type { IWithdrawRepository } from "@/modules/payments/interfaces/withdraw-repository.interface";
import type { IPaymentWebhookRepository } from "@/modules/payments/interfaces/payment-webhook-repository.interface";
import type {
  IGatewayCredentialRepository,
  CreateGatewayCredentialInput,
  UpdateGatewayCredentialInput,
} from "@/modules/payments/interfaces/gateway-credential-repository.interface";
import type { IGatewayLogRepository } from "@/modules/payments/interfaces/gateway-log-repository.interface";
import type { IPaymentSettingsRepository, UpdatePaymentSettingsInput } from "@/modules/payments/interfaces/payment-settings-repository.interface";
import type { PaymentProvider } from "@/modules/payments/interfaces/payment-provider.interface";
import type {
  Deposit,
  DepositAdminRow,
  WithdrawAdminRow,
  DepositStatus,
  GatewayCredential,
  GatewayCredentialWithHealth,
  PaymentWebhook,
  PaymentSettings,
  GatewayProvider,
  PaymentRelatedType,
} from "@/modules/payments/entities/payments.entity";
import type { DepositListFilter } from "@/modules/payments/interfaces/deposit-repository.interface";
import type { WithdrawListFilter } from "@/modules/payments/interfaces/withdraw-repository.interface";
import type { PaymentWebhookListFilter } from "@/modules/payments/interfaces/payment-webhook-repository.interface";
import type { GatewayLogListFilter } from "@/modules/payments/interfaces/gateway-log-repository.interface";
import type { GatewayCredentialListFilter } from "@/modules/payments/interfaces/gateway-credential-repository.interface";

export interface CreateDepositResult {
  depositId: string;
  pixCode: string;
  qrCodeUrl: string | null;
  expiresAt: string | null;
  amountCents: number;
  status: DepositStatus;
  /** Whether "Simular Pagamento" is a valid next step for this deposit — true only for MOCK, so the UI never offers a fake-payment button against a real gateway. */
  canSimulate: boolean;
}

export interface RequestWithdrawResult {
  withdrawId: string;
  status: string;
  amountCents: number;
}

const SYSTEM_ACTOR: WalletActor = { actorId: null, actorType: "SYSTEM" };

/**
 * The financial core's only bridge to the outside world. Never moves a
 * balance itself — every confirmed deposit or approved/rejected withdraw
 * calls into `WalletService` (credit/debit/lock/unlock), which stays the
 * sole writer of Wallet balances (see that module's README). This class
 * owns: gateway selection + failover (via GatewayRouterService), the
 * Deposit/Withdraw/PaymentWebhook lifecycle, and webhook signature
 * verification + idempotent settlement.
 */
export class PaymentService {
  private readonly dispatcher: WebhookDispatcherService;

  constructor(
    private readonly deposits: IDepositRepository,
    private readonly withdraws: IWithdrawRepository,
    private readonly webhooks: IPaymentWebhookRepository,
    private readonly credentials: IGatewayCredentialRepository,
    private readonly logs: IGatewayLogRepository,
    private readonly settingsRepo: IPaymentSettingsRepository,
    private readonly router: GatewayRouterService,
    private readonly walletService: WalletService,
    private readonly users: IUserRepository
  ) {
    this.dispatcher = new WebhookDispatcherService(
      webhooks,
      credentials,
      logs,
      this.resolveRelatedId.bind(this),
      this.settle.bind(this)
    );
  }

  /** Contas Demo (src/modules/demo-accounts) são exclusivamente demonstrativas — nunca movimentam dinheiro real. */
  private async assertNotDemo(userId: string, action: "depositar" | "sacar"): Promise<void> {
    const user = await this.users.findById(userId);
    if (user?.isDemo) {
      throw new BusinessRuleError(`Contas Demo não podem ${action}`);
    }
  }

  // -------------------------------------------------------------- deposits

  async createDeposit(userId: string, amountCents: number): Promise<CreateDepositResult> {
    await this.assertNotDemo(userId, "depositar");
    const settings = await this.settingsRepo.get();
    if (amountCents < settings.depositMinCents || amountCents > settings.depositMaxCents) {
      throw new BusinessRuleError(
        `Valor deve estar entre ${settings.depositMinCents / 100} e ${settings.depositMaxCents / 100}`
      );
    }

    const depositId = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + settings.pixExpirationMinutes * 60_000);
    const user = await this.users.findById(userId);

    const { credential, result } = await this.withFailover(
      settings,
      "/api/payments/deposits",
      depositId,
      (provider) =>
        provider.createPixDeposit({
          depositId,
          amountCents,
          expiresAt,
          payerName: user ? `${user.firstName} ${user.lastName}`.trim() : undefined,
          // Phone-only signup means user.email is almost always a synthetic
          // @player.helixcoin.internal address now (see auto-identity.util.ts)
          // — an unresolvable domain that gateways can silently reject as
          // the payer's email, exactly the "HTTP 200, no error message"
          // failure this guards against. Omit it; providers already fall
          // back to a safe placeholder when payerEmail is undefined.
          payerEmail: user && !isAutoGeneratedEmail(user.email) ? user.email : undefined,
          payerPhone: user?.phone ?? undefined,
          payerDocument: user?.cpf ?? undefined,
        })
    );

    const deposit = await this.deposits.create({
      id: depositId,
      userId,
      gatewayCredentialId: credential.id,
      amountCents,
      status: "PENDING",
      providerTransactionId: result.providerTransactionId,
      pixCode: result.pixCode,
      qrCodeUrl: result.qrCodeUrl ?? null,
      expiresAt: result.expiresAt,
    });

    eventBus.publish(PAYMENT_EVENTS.depositCreated, {
      depositId: deposit.id,
      userId,
      amountCents,
      gatewayCredentialId: credential.id,
      status: deposit.status,
    });
    eventBus.publish(PAYMENT_EVENTS.depositPending, {
      depositId: deposit.id,
      userId,
      amountCents,
      gatewayCredentialId: credential.id,
      status: deposit.status,
    });

    return {
      depositId: deposit.id,
      pixCode: deposit.pixCode!,
      qrCodeUrl: deposit.qrCodeUrl,
      expiresAt: deposit.expiresAt ? deposit.expiresAt.toISOString() : null,
      amountCents: deposit.amountCents,
      status: deposit.status,
      canSimulate: credential.provider === "MOCK",
    };
  }

  async getDeposit(depositId: string, userId: string): Promise<Deposit> {
    const deposit = await this.deposits.findById(depositId);
    if (!deposit) throw new NotFoundError("Depósito");
    if (deposit.userId !== userId) throw new ForbiddenError();
    return deposit;
  }

  /** Player-facing Mock-only demo action — guarded to the MOCK provider, builds a real signed webhook payload and settles it through the exact same path a real webhook would. */
  async simulateDeposit(depositId: string, userId: string, outcome: "PAID" | "FAILED"): Promise<{ status: number }> {
    const deposit = await this.deposits.findById(depositId);
    if (!deposit) throw new NotFoundError("Depósito");
    if (deposit.userId !== userId) throw new ForbiddenError();
    if (deposit.status !== "PENDING") throw new BusinessRuleError("Depósito já processado");

    const credential = await this.credentials.findById(deposit.gatewayCredentialId);
    if (!credential || credential.provider !== "MOCK") {
      throw new BusinessRuleError("Simulação disponível apenas para o gateway MOCK");
    }

    const webhookSecret = decrypt(credential.webhookSecretEncrypted);
    const built = MockProvider.buildWebhookPayload({
      eventType: outcome === "PAID" ? "deposit.paid" : "deposit.failed",
      relatedType: "DEPOSIT",
      relatedId: deposit.id,
      providerTransactionId: deposit.providerTransactionId ?? `mock_dep_${deposit.id}`,
      webhookSecret,
    });

    return this.dispatcher.dispatch(credential.provider, built.rawBody, built.signatureHeader);
  }

  // ------------------------------------------------------------- withdraws

  async requestWithdraw(
    userId: string,
    amountCents: number,
    pixKey: string,
    pixKeyType: string | undefined,
    actor: WalletActor
  ): Promise<RequestWithdrawResult> {
    await this.assertNotDemo(userId, "sacar");
    const settings = await this.settingsRepo.get();
    if (amountCents < settings.withdrawMinCents || amountCents > settings.withdrawMaxCents) {
      throw new BusinessRuleError(
        `Valor deve estar entre ${settings.withdrawMinCents / 100} e ${settings.withdrawMaxCents / 100}`
      );
    }

    const withdrawId = crypto.randomUUID();
    const user = await this.users.findById(userId);

    const locked = await this.walletService.lock({
      userId,
      amountCents,
      type: "WITHDRAW_PENDING",
      origin: "payments",
      originId: withdrawId,
      idempotencyKey: PAYMENT_IDEMPOTENCY_KEYS.withdrawLock(withdrawId),
      metadata: { pixKeyMasked: maskPixKey(pixKey) },
      actor,
    });

    let credential: GatewayCredential;
    let providerTransactionId: string;
    try {
      const outcome = await this.withFailover(settings, "/api/payments/withdrawals", withdrawId, (provider) =>
        provider.createWithdraw({
          withdrawId,
          amountCents,
          pixKey,
          pixKeyType,
          payeeName: user ? `${user.firstName} ${user.lastName}`.trim() : undefined,
          payeeDocument: user?.cpf ?? undefined,
          payerIp: actor.ip ?? undefined,
        })
      );
      credential = outcome.credential;
      providerTransactionId = outcome.result.providerTransactionId;
    } catch (err) {
      // Every candidate gateway rejected the request — never leave funds stuck locked with no gateway holding it.
      await this.walletService.unlock({
        userId,
        amountCents,
        type: "WITHDRAW_REJECTED",
        origin: "payments",
        originId: withdrawId,
        idempotencyKey: PAYMENT_IDEMPOTENCY_KEYS.withdrawUnlockProviderFailure(withdrawId),
        metadata: { reason: "gateway_unavailable" },
        actor: SYSTEM_ACTOR,
      });
      throw err;
    }

    const withdraw = await this.withdraws.create({
      id: withdrawId,
      userId,
      gatewayCredentialId: credential.id,
      amountCents,
      status: "PENDING",
      pixKeyEncrypted: encrypt(pixKey),
      pixKeyType: pixKeyType ?? null,
      providerTransactionId,
      lockWalletTransactionId: locked.transaction.id,
    });

    eventBus.publish(PAYMENT_EVENTS.withdrawRequested, {
      withdrawId: withdraw.id,
      userId,
      amountCents,
      gatewayCredentialId: credential.id,
      status: withdraw.status,
    });

    return { withdrawId: withdraw.id, status: withdraw.status, amountCents };
  }

  /** Admin-only Mock-only decision action — same "build a real signed webhook payload, settle through handleWebhook" pattern as simulateDeposit. */
  async decideWithdraw(
    withdrawId: string,
    action: "APPROVE" | "REJECT",
    rejectionReason: string | undefined
  ): Promise<{ status: number }> {
    const withdraw = await this.withdraws.findById(withdrawId);
    if (!withdraw) throw new NotFoundError("Saque");
    if (withdraw.status !== "PENDING") throw new BusinessRuleError("Saque já processado");

    const credential = await this.credentials.findById(withdraw.gatewayCredentialId);
    if (!credential || credential.provider !== "MOCK") {
      throw new BusinessRuleError("Simulação disponível apenas para o gateway MOCK");
    }

    const webhookSecret = decrypt(credential.webhookSecretEncrypted);
    const built = MockProvider.buildWebhookPayload({
      eventType: action === "APPROVE" ? "withdraw.approved" : "withdraw.rejected",
      relatedType: "WITHDRAW",
      relatedId: withdraw.id,
      providerTransactionId: withdraw.providerTransactionId ?? `mock_wd_${withdraw.id}`,
      webhookSecret,
      extra: action === "REJECT" ? { rejectionReason } : undefined,
    });

    return this.dispatcher.dispatch(credential.provider, built.rawBody, built.signatureHeader);
  }

  /**
   * Admin-only Fase 10 simulator — same "build a real signed webhook
   * payload, settle through the dispatcher" pattern as simulateDeposit/
   * decideWithdraw, but with the fuller outcome set (CANCELLED/EXPIRED/
   * REFUNDED) that only makes sense as an ops/testing action, never
   * something a player triggers on their own deposit — the player-facing
   * simulateDeposit above is untouched, still PAID/FAILED only.
   */
  async simulateDepositAdmin(
    depositId: string,
    outcome: "PAID" | "FAILED" | "CANCELLED" | "EXPIRED" | "REFUNDED"
  ): Promise<{ status: number }> {
    const deposit = await this.deposits.findById(depositId);
    if (!deposit) throw new NotFoundError("Depósito");

    const requiredStatus = outcome === "REFUNDED" ? "PAID" : "PENDING";
    if (deposit.status !== requiredStatus) {
      throw new BusinessRuleError(
        outcome === "REFUNDED" ? "Só é possível estornar um depósito já pago" : "Depósito já processado"
      );
    }

    const credential = await this.credentials.findById(deposit.gatewayCredentialId);
    if (!credential || credential.provider !== "MOCK") {
      throw new BusinessRuleError("Simulação disponível apenas para o gateway MOCK");
    }

    const eventTypeByOutcome: Record<typeof outcome, string> = {
      PAID: "deposit.paid",
      FAILED: "deposit.failed",
      CANCELLED: "deposit.cancelled",
      EXPIRED: "deposit.expired",
      REFUNDED: "deposit.refunded",
    };

    const webhookSecret = decrypt(credential.webhookSecretEncrypted);
    const built = MockProvider.buildWebhookPayload({
      eventType: eventTypeByOutcome[outcome],
      relatedType: "DEPOSIT",
      relatedId: deposit.id,
      providerTransactionId: deposit.providerTransactionId ?? `mock_dep_${deposit.id}`,
      webhookSecret,
    });

    return this.dispatcher.dispatch(credential.provider, built.rawBody, built.signatureHeader);
  }

  // -------------------------------------------------------------- webhooks

  /** Thin delegation — the mechanics of matching/dedup/persistence live in WebhookDispatcherService (Fase 10); this stays public so `/api/payments/webhook/{provider}` doesn't need to know that split happened. `timestampHeader` is only meaningful to gateways whose signature scheme includes it (e.g. VeoPag) — providers that don't need it simply ignore it. */
  async handleWebhook(
    providerName: GatewayProvider,
    rawBody: string,
    signatureHeader: string | null,
    timestampHeader?: string | null
  ): Promise<{ status: number }> {
    return this.dispatcher.dispatch(providerName, rawBody, signatureHeader, timestampHeader);
  }

  /** Admin "Reprocessar" action on a stored webhook. */
  async reprocessWebhook(webhookId: string): Promise<{ status: number }> {
    return this.dispatcher.reprocess(webhookId);
  }

  private async resolveRelatedId(relatedType: PaymentRelatedType, providerTransactionId: string): Promise<string | null> {
    if (relatedType === "DEPOSIT") {
      const deposit = await this.deposits.findByProviderTransactionId(providerTransactionId);
      return deposit?.id ?? null;
    }
    const withdraw = await this.withdraws.findByProviderTransactionId(providerTransactionId);
    return withdraw?.id ?? null;
  }

  /**
   * The settlement idempotency-key scheme, parallel to match-engine's
   * `match:{id}:bet` convention:
   *   deposit.paid              -> credit()                       deposit:{id}:confirm
   *   deposit.failed/cancelled/
   *   expired/refunded          -> Deposit status update only      (none)
   *   withdraw.approved         -> debit(account:"LOCKED")         withdraw:{id}:approve
   *   withdraw.rejected         -> unlock()                        withdraw:{id}:unlock-reject
   * Every branch is itself defensively idempotent (checks the current
   * Deposit/Withdraw status before acting) on top of WalletService's own
   * idempotency-key guarantee — belt and suspenders for a reprocessed or
   * replayed webhook. When the guard trips because the entity already moved
   * past the state this event expects (e.g. a stale "rejected" landing
   * after the withdraw was already APPROVED), it's a no-op AND publishes
   * PAYMENT_EVENTS.webhookOutOfOrder (Fase 10) instead of failing silently.
   *
   * deposit.refunded is status-only by design (Fase 10) — it never calls
   * WalletService. Automatically reversing an already-spent deposit's
   * balance is a real business-risk decision (negative balance handling,
   * etc.) that's out of scope for the payments architecture hardening this
   * phase covers; if a refund needs an actual balance adjustment, the admin
   * already has the right tool for that (the audited manual wallet
   * adjustment at /admin/wallets).
   */
  private async settle(webhook: PaymentWebhook): Promise<void> {
    switch (webhook.eventType) {
      case "deposit.paid": {
        const deposit = await this.deposits.findById(webhook.relatedId);
        if (!deposit) throw new NotFoundError("Depósito");
        if (deposit.status === "PAID") {
          this.publishWebhookOutOfOrder(webhook, deposit.status);
          return;
        }

        const result = await this.walletService.credit({
          userId: deposit.userId,
          amountCents: deposit.amountCents,
          type: "DEPOSIT",
          origin: "payments",
          originId: deposit.id,
          idempotencyKey: PAYMENT_IDEMPOTENCY_KEYS.depositConfirm(deposit.id),
          metadata: { gatewayCredentialId: deposit.gatewayCredentialId, provider: webhook.provider },
          actor: SYSTEM_ACTOR,
        });

        await this.deposits.update(deposit.id, {
          status: "PAID",
          walletTransactionId: result.transaction.id,
          confirmedAt: new Date(),
        });
        eventBus.publish(PAYMENT_EVENTS.depositConfirmed, {
          depositId: deposit.id,
          userId: deposit.userId,
          amountCents: deposit.amountCents,
          gatewayCredentialId: deposit.gatewayCredentialId,
          status: "PAID",
        });
        return;
      }

      case "deposit.failed":
      case "deposit.cancelled":
      case "deposit.expired": {
        const deposit = await this.deposits.findById(webhook.relatedId);
        if (!deposit) throw new NotFoundError("Depósito");
        if (deposit.status !== "PENDING" && deposit.status !== "PROCESSING") {
          this.publishWebhookOutOfOrder(webhook, deposit.status);
          return;
        }

        const statusMap: Record<string, DepositStatus> = {
          "deposit.failed": "FAILED",
          "deposit.cancelled": "CANCELLED",
          "deposit.expired": "EXPIRED",
        };
        const eventByType = {
          "deposit.failed": PAYMENT_EVENTS.depositFailed,
          "deposit.cancelled": PAYMENT_EVENTS.depositCancelled,
          "deposit.expired": PAYMENT_EVENTS.depositExpired,
        } as const;
        const reason = (webhook.payload as { reason?: string }).reason ?? null;
        await this.deposits.update(deposit.id, { status: statusMap[webhook.eventType], failureReason: reason });
        eventBus.publish(eventByType[webhook.eventType as keyof typeof eventByType], {
          depositId: deposit.id,
          userId: deposit.userId,
          amountCents: deposit.amountCents,
          gatewayCredentialId: deposit.gatewayCredentialId,
          status: statusMap[webhook.eventType],
        });
        return;
      }

      case "deposit.refunded": {
        const deposit = await this.deposits.findById(webhook.relatedId);
        if (!deposit) throw new NotFoundError("Depósito");
        if (deposit.status !== "PAID") {
          this.publishWebhookOutOfOrder(webhook, deposit.status);
          return;
        }

        await this.deposits.update(deposit.id, { status: "REFUNDED" });
        eventBus.publish(PAYMENT_EVENTS.depositRefunded, {
          depositId: deposit.id,
          userId: deposit.userId,
          amountCents: deposit.amountCents,
          gatewayCredentialId: deposit.gatewayCredentialId,
          status: "REFUNDED",
        });
        return;
      }

      case "withdraw.approved": {
        const withdraw = await this.withdraws.findById(webhook.relatedId);
        if (!withdraw) throw new NotFoundError("Saque");
        if (withdraw.status !== "PENDING" && withdraw.status !== "PROCESSING") {
          this.publishWebhookOutOfOrder(webhook, withdraw.status);
          return;
        }

        const result = await this.walletService.debit({
          userId: withdraw.userId,
          amountCents: withdraw.amountCents,
          type: "WITHDRAW_APPROVED",
          account: "LOCKED",
          origin: "payments",
          originId: withdraw.id,
          idempotencyKey: PAYMENT_IDEMPOTENCY_KEYS.withdrawApprove(withdraw.id),
          actor: SYSTEM_ACTOR,
        });

        await this.withdraws.update(withdraw.id, {
          status: "APPROVED",
          settleWalletTransactionId: result.transaction.id,
          processedAt: new Date(),
        });
        eventBus.publish(PAYMENT_EVENTS.withdrawApproved, {
          withdrawId: withdraw.id,
          userId: withdraw.userId,
          amountCents: withdraw.amountCents,
          gatewayCredentialId: withdraw.gatewayCredentialId,
          status: "APPROVED",
        });
        return;
      }

      case "withdraw.rejected": {
        const withdraw = await this.withdraws.findById(webhook.relatedId);
        if (!withdraw) throw new NotFoundError("Saque");
        if (withdraw.status !== "PENDING" && withdraw.status !== "PROCESSING") {
          this.publishWebhookOutOfOrder(webhook, withdraw.status);
          return;
        }

        await this.walletService.unlock({
          userId: withdraw.userId,
          amountCents: withdraw.amountCents,
          type: "WITHDRAW_REJECTED",
          origin: "payments",
          originId: withdraw.id,
          idempotencyKey: PAYMENT_IDEMPOTENCY_KEYS.withdrawUnlockReject(withdraw.id),
          actor: SYSTEM_ACTOR,
        });

        const rejectionReason = (webhook.payload as { rejectionReason?: string }).rejectionReason ?? null;
        await this.withdraws.update(withdraw.id, {
          status: "REJECTED",
          rejectionReason,
          processedAt: new Date(),
        });
        eventBus.publish(PAYMENT_EVENTS.withdrawRejected, {
          withdrawId: withdraw.id,
          userId: withdraw.userId,
          amountCents: withdraw.amountCents,
          gatewayCredentialId: withdraw.gatewayCredentialId,
          status: "REJECTED",
        });
        return;
      }

      default:
        throw new BusinessRuleError(`Evento de webhook desconhecido: ${webhook.eventType}`);
    }
  }

  private publishWebhookOutOfOrder(webhook: PaymentWebhook, currentStatus: string): void {
    eventBus.publish(PAYMENT_EVENTS.webhookOutOfOrder, {
      webhookId: webhook.id,
      relatedType: webhook.relatedType,
      relatedId: webhook.relatedId,
      currentStatus,
      attemptedEventType: webhook.eventType,
    });
  }

  // ---------------------------------------------------------- gateway I/O

  /**
   * Tries every routable, healthy candidate in order; per candidate, retries
   * up to `credential.maxRetries` times (Fase 10 — previously a stored-but-
   * unread column) before moving on, and every single attempt is bounded by
   * `credential.timeoutMs` via `withTimeout`. `correlationId` is always the
   * Deposit/Withdraw id — the same value threaded through every GatewayLog
   * row, the eventual PaymentWebhook, and the WalletService call that
   * settles it, so the whole chain (gateway attempts → webhook → wallet →
   * ledger → logs) can be reconstructed from one id alone. Records a
   * GatewayLog row per attempt and a fresh health check once a candidate's
   * retries are exhausted, so the next call's routing already reflects it.
   */
  private async withFailover<T>(
    settings: PaymentSettings,
    endpoint: string,
    correlationId: string,
    fn: (provider: PaymentProvider) => Promise<T>
  ): Promise<{ credential: GatewayCredential; result: T }> {
    const ordered = await this.router.resolveCandidates(settings);
    const healthy = await this.router.filterHealthy(ordered);
    const candidates = healthy.length > 0 ? healthy : ordered;
    if (candidates.length === 0) throw new BusinessRuleError("Nenhum gateway de pagamento ativo configurado");

    let lastError: unknown;
    for (let i = 0; i < candidates.length; i++) {
      const credential = candidates[i];
      const provider = ProviderFactory.create(credential);
      const maxAttempts = credential.maxRetries + 1;

      let candidateError: unknown;
      for (let attempt = 0; attempt < maxAttempts; attempt++) {
        if (attempt > 0) {
          eventBus.publish(PAYMENT_EVENTS.gatewayRetry, {
            gatewayCredentialId: credential.id,
            provider: credential.provider,
            correlationId,
            attempt,
            maxRetries: credential.maxRetries,
          });
        }

        const start = performance.now();
        try {
          const result = await this.withTimeout(fn(provider), credential.timeoutMs);
          const durationMs = Math.round(performance.now() - start);
          await this.logGateway({
            direction: "outbound",
            endpoint,
            provider: credential.provider,
            gatewayCredentialId: credential.id,
            success: true,
            durationMs,
            correlationId,
            requestSummary: { correlationId, attempt, maxRetries: credential.maxRetries },
          });
          return { credential, result };
        } catch (err) {
          candidateError = err;
          lastError = err;
          const timedOut = err instanceof GatewayTimeoutError;
          const durationMs = Math.round(performance.now() - start);

          if (timedOut) {
            eventBus.publish(PAYMENT_EVENTS.gatewayTimeout, {
              gatewayCredentialId: credential.id,
              provider: credential.provider,
              correlationId,
              attempt,
              timeoutMs: credential.timeoutMs,
            });
          }

          await this.logGateway({
            direction: "outbound",
            endpoint,
            provider: credential.provider,
            gatewayCredentialId: credential.id,
            success: false,
            durationMs,
            correlationId,
            errorMessage: timedOut ? `timeout after ${credential.timeoutMs}ms` : err instanceof Error ? err.message : "unknown error",
            requestSummary: { correlationId, attempt, maxRetries: credential.maxRetries, timedOut },
          });
        }
      }

      // Every attempt for this candidate failed — record health and move to the next one.
      await this.router.recordHealthCheck(credential).catch(() => {});
      const next = candidates[i + 1];
      eventBus.publish(PAYMENT_EVENTS.gatewayFailover, {
        fromGatewayCredentialId: credential.id,
        toGatewayCredentialId: next ? next.id : null,
        provider: credential.provider,
        correlationId,
        reason: candidateError instanceof Error ? candidateError.message : "unknown error",
      });
    }

    throw lastError instanceof Error
      ? new ExternalServiceError("payments", lastError.message)
      : new ExternalServiceError("payments");
  }

  /** Races `promise` against a timer that rejects with GatewayTimeoutError after `timeoutMs` — never leaves a dangling timer once either side settles. */
  private withTimeout<T>(promise: Promise<T>, timeoutMs: number): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      const timer = setTimeout(() => reject(new GatewayTimeoutError(timeoutMs)), timeoutMs);
      promise.then(
        (value) => {
          clearTimeout(timer);
          resolve(value);
        },
        (err) => {
          clearTimeout(timer);
          reject(err);
        }
      );
    });
  }

  private async logGateway(input: {
    direction: "outbound" | "inbound";
    endpoint: string;
    provider?: GatewayProvider | null;
    gatewayCredentialId?: string | null;
    success: boolean;
    durationMs?: number;
    statusCode?: number;
    correlationId?: string;
    errorMessage?: string;
    requestSummary?: Record<string, unknown>;
  }): Promise<void> {
    try {
      await this.logs.create({
        gatewayCredentialId: input.gatewayCredentialId ?? null,
        provider: input.provider ?? null,
        direction: input.direction,
        endpoint: input.endpoint,
        success: input.success,
        durationMs: input.durationMs ?? null,
        statusCode: input.statusCode ?? null,
        errorMessage: input.errorMessage ?? null,
        correlationId: input.correlationId ?? null,
        requestSummary: input.requestSummary ?? (input.correlationId ? { correlationId: input.correlationId } : null),
      });
    } catch {
      // Logging must never break the payment flow itself.
    }
  }

  // ------------------------------------------------------------- admin

  async listDepositsAdmin(filter: DepositListFilter) {
    return this.deposits.listAdmin(filter);
  }

  async getDepositAdmin(id: string): Promise<DepositAdminRow> {
    const deposit = await this.deposits.findByIdAdmin(id);
    if (!deposit) throw new NotFoundError("Depósito");
    return deposit;
  }

  async listWithdrawsAdmin(filter: WithdrawListFilter) {
    const { items, total } = await this.withdraws.listAdmin(filter);
    return {
      items: items.map((row) => ({ row, pixKeyMasked: maskPixKey(decrypt(row.pixKeyEncrypted)) })),
      total,
    };
  }

  async getWithdrawAdmin(id: string): Promise<{ withdraw: WithdrawAdminRow; pixKeyMasked: string }> {
    const withdraw = await this.withdraws.findByIdAdmin(id);
    if (!withdraw) throw new NotFoundError("Saque");
    return { withdraw, pixKeyMasked: maskPixKey(decrypt(withdraw.pixKeyEncrypted)) };
  }

  async listWebhooksAdmin(filter: PaymentWebhookListFilter) {
    return this.webhooks.listAdmin(filter);
  }

  async getWebhookAdmin(id: string): Promise<PaymentWebhook> {
    const webhook = await this.webhooks.findById(id);
    if (!webhook) throw new NotFoundError("Webhook");
    return webhook;
  }

  async listGatewayLogsAdmin(filter: GatewayLogListFilter) {
    return this.logs.listAdmin(filter);
  }

  async listGatewaysAdmin(filter: GatewayCredentialListFilter): Promise<{ items: GatewayCredentialWithHealth[]; total: number }> {
    return this.credentials.listAdmin(filter);
  }

  async getGatewayAdmin(id: string): Promise<GatewayCredentialWithHealth> {
    const credential = await this.credentials.findById(id);
    if (!credential) throw new NotFoundError("Gateway");
    const { items } = await this.credentials.listAdmin({ page: 1, pageSize: 1000 });
    return items.find((c) => c.id === id) ?? { ...credential, latestHealth: null };
  }

  async createGateway(input: {
    name: string;
    provider: GatewayProvider;
    mode?: "SANDBOX" | "PRODUCTION";
    credentials: Record<string, unknown>;
    webhookSecret: string;
    active?: boolean;
    priority?: number;
    weight?: number;
    timeoutMs?: number;
    maxRetries?: number;
    simulatedHealth?: GatewayCredential["simulatedHealth"];
    simulatedErrorMode?: GatewayCredential["simulatedErrorMode"];
    createdById: string;
  }): Promise<GatewayCredential> {
    const payload: CreateGatewayCredentialInput = {
      name: input.name,
      provider: input.provider,
      mode: input.mode,
      active: input.active,
      priority: input.priority,
      weight: input.weight,
      timeoutMs: input.timeoutMs,
      maxRetries: input.maxRetries,
      credentialsEncrypted: encrypt(JSON.stringify(input.credentials)),
      webhookSecretEncrypted: encrypt(input.webhookSecret),
      simulatedHealth: input.simulatedHealth ?? null,
      simulatedErrorMode: input.simulatedErrorMode ?? null,
      createdById: input.createdById,
    };
    return this.credentials.create(payload);
  }

  async updateGateway(
    id: string,
    input: {
      name?: string;
      mode?: "SANDBOX" | "PRODUCTION";
      credentials?: Record<string, unknown>;
      webhookSecret?: string;
      active?: boolean;
      priority?: number;
      weight?: number;
      timeoutMs?: number;
      maxRetries?: number;
      simulatedHealth?: GatewayCredential["simulatedHealth"];
      simulatedErrorMode?: GatewayCredential["simulatedErrorMode"];
    }
  ): Promise<GatewayCredential> {
    const existing = await this.credentials.findById(id);
    if (!existing) throw new NotFoundError("Gateway");

    const payload: UpdateGatewayCredentialInput = {
      name: input.name,
      mode: input.mode,
      active: input.active,
      priority: input.priority,
      weight: input.weight,
      timeoutMs: input.timeoutMs,
      maxRetries: input.maxRetries,
      simulatedHealth: input.simulatedHealth,
      simulatedErrorMode: input.simulatedErrorMode,
      ...(input.credentials !== undefined ? { credentialsEncrypted: encrypt(JSON.stringify(input.credentials)) } : {}),
      ...(input.webhookSecret !== undefined ? { webhookSecretEncrypted: encrypt(input.webhookSecret) } : {}),
    };
    return this.credentials.update(id, payload);
  }

  async testGatewayConnection(id: string) {
    const credential = await this.credentials.findById(id);
    if (!credential) throw new NotFoundError("Gateway");
    return this.router.recordHealthCheck(credential);
  }

  async getSettings(): Promise<PaymentSettings> {
    return this.settingsRepo.get();
  }

  async updateSettings(input: UpdatePaymentSettingsInput): Promise<PaymentSettings> {
    return this.settingsRepo.update(input);
  }
}
